export const ACTIVATION_CODE_BATCH_REVOKE_SCOPES = [
  "UNASSIGNED_ONLY",
  "ALL_REVOCABLE",
] as const;

export const DEFAULT_ACTIVATION_CODE_BATCH_REVOKE_SCOPE =
  "UNASSIGNED_ONLY" as const;

export const MAX_ACTIVATION_CODES_PER_PRODUCT_ASSIGNMENT = 100;

export const MAX_AUTOMATIC_ACTIVATION_CODES_PER_PRODUCT_ASSIGNMENT = 1000;

export const ACTIVATION_CODE_PRODUCT_ASSIGNMENT_MODES = [
  "SELECTED",
  "ALL_AVAILABLE",
  "QUANTITY",
] as const;

export type ActivationCodeProductAssignmentMode =
  (typeof ACTIVATION_CODE_PRODUCT_ASSIGNMENT_MODES)[number];
