export const ACTIVATION_LABEL_PRINTABLE_WIDTH_MM = 182.8;
export const ACTIVATION_LABEL_PRINTABLE_HEIGHT_MM = 270.4;
export const DEFAULT_ACTIVATION_LABEL_WIDTH_MM = 45.7;
export const DEFAULT_ACTIVATION_LABEL_HEIGHT_MM = 16.9;
export const MIN_ACTIVATION_LABEL_WIDTH_MM = 30;
export const MIN_ACTIVATION_LABEL_HEIGHT_MM = 12;
