export const NOTIFICATION_TYPES = {
  WARRANTY_CLAIM_CREATED: "WARRANTY_CLAIM_CREATED",
  WARRANTY_CLAIM_STATUS_CHANGED: "WARRANTY_CLAIM_STATUS_CHANGED",
  WARRANTY_CLAIM_ASSIGNED_SERVICE_CENTER:
    "WARRANTY_CLAIM_ASSIGNED_SERVICE_CENTER",
  WARRANTY_CLAIM_SLA_BREACHED: "WARRANTY_CLAIM_SLA_BREACHED",
  WARRANTY_ACTIVATION_REQUEST_CREATED: "WARRANTY_ACTIVATION_REQUEST_CREATED",
  CONTACT_SUBMISSION_CREATED: "CONTACT_SUBMISSION_CREATED",
  SYSTEM_ALERT: "SYSTEM_ALERT",
  ANNOUNCEMENT: "ANNOUNCEMENT",
} as const;

export type NotificationType =
  (typeof NOTIFICATION_TYPES)[keyof typeof NOTIFICATION_TYPES];
