import type { UserRole } from "./roles.ts";

export const PERMISSIONS = {
  DASHBOARD_VIEW: "DASHBOARD_VIEW",

  CUSTOMER_VIEW: "CUSTOMER_VIEW",
  CUSTOMER_CREATE: "CUSTOMER_CREATE",
  CUSTOMER_UPDATE: "CUSTOMER_UPDATE",
  CUSTOMER_DELETE: "CUSTOMER_DELETE",

  PRODUCT_VIEW: "PRODUCT_VIEW",
  PRODUCT_CREATE: "PRODUCT_CREATE",
  PRODUCT_UPDATE: "PRODUCT_UPDATE",
  PRODUCT_DELETE: "PRODUCT_DELETE",
  PRODUCT_ASSIGN_OWNER: "PRODUCT_ASSIGN_OWNER",

  WARRANTY_VIEW: "WARRANTY_VIEW",
  WARRANTY_CREATE: "WARRANTY_CREATE",
  WARRANTY_UPDATE: "WARRANTY_UPDATE",
  WARRANTY_ACTIVATE: "WARRANTY_ACTIVATE",
  WARRANTY_VOID: "WARRANTY_VOID",
  WARRANTY_LOOKUP_OWN: "WARRANTY_LOOKUP_OWN",

  WARRANTY_CLAIM_VIEW: "WARRANTY_CLAIM_VIEW",
  WARRANTY_CLAIM_CREATE: "WARRANTY_CLAIM_CREATE",
  WARRANTY_CLAIM_UPDATE: "WARRANTY_CLAIM_UPDATE",
  WARRANTY_CLAIM_STATUS_UPDATE: "WARRANTY_CLAIM_STATUS_UPDATE",

  SERVICE_CENTER_VIEW: "SERVICE_CENTER_VIEW",
  SERVICE_CENTER_CREATE: "SERVICE_CENTER_CREATE",
  SERVICE_CENTER_UPDATE: "SERVICE_CENTER_UPDATE",
  SERVICE_CENTER_DELETE: "SERVICE_CENTER_DELETE",

  DEALER_VIEW: "DEALER_VIEW",
  DEALER_CREATE: "DEALER_CREATE",
  DEALER_UPDATE: "DEALER_UPDATE",
  DEALER_DELETE: "DEALER_DELETE",

  CONTENT_PAGE_VIEW: "CONTENT_PAGE_VIEW",
  CONTENT_PAGE_CREATE: "CONTENT_PAGE_CREATE",
  CONTENT_PAGE_UPDATE: "CONTENT_PAGE_UPDATE",
  CONTENT_PAGE_DELETE: "CONTENT_PAGE_DELETE",

  CATEGORY_VIEW: "CATEGORY_VIEW",
  CATEGORY_CREATE: "CATEGORY_CREATE",
  CATEGORY_UPDATE: "CATEGORY_UPDATE",
  CATEGORY_DELETE: "CATEGORY_DELETE",

  USER_VIEW: "USER_VIEW",
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",
  USER_DELETE: "USER_DELETE",
  USER_PERMISSION_MANAGE: "USER_PERMISSION_MANAGE",

  SYSTEM_VIEW: "SYSTEM_VIEW",
  AUDIT_LOG_VIEW: "AUDIT_LOG_VIEW",
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ALL_PERMISSIONS = Object.values(PERMISSIONS);

export const PERMISSION_GROUPS = [
  {
    key: "dashboard",
    label: "Dashboard",
    permissions: [PERMISSIONS.DASHBOARD_VIEW],
  },
  {
    key: "customers",
    label: "Customers",
    permissions: [
      PERMISSIONS.CUSTOMER_VIEW,
      PERMISSIONS.CUSTOMER_CREATE,
      PERMISSIONS.CUSTOMER_UPDATE,
      PERMISSIONS.CUSTOMER_DELETE,
    ],
  },
  {
    key: "products",
    label: "Products",
    permissions: [
      PERMISSIONS.PRODUCT_VIEW,
      PERMISSIONS.PRODUCT_CREATE,
      PERMISSIONS.PRODUCT_UPDATE,
      PERMISSIONS.PRODUCT_DELETE,
      PERMISSIONS.PRODUCT_ASSIGN_OWNER,
    ],
  },
  {
    key: "warranties",
    label: "Warranties",
    permissions: [
      PERMISSIONS.WARRANTY_VIEW,
      PERMISSIONS.WARRANTY_CREATE,
      PERMISSIONS.WARRANTY_UPDATE,
      PERMISSIONS.WARRANTY_ACTIVATE,
      PERMISSIONS.WARRANTY_VOID,
      PERMISSIONS.WARRANTY_LOOKUP_OWN,
    ],
  },
  {
    key: "warrantyClaims",
    label: "Warranty Claims",
    permissions: [
      PERMISSIONS.WARRANTY_CLAIM_VIEW,
      PERMISSIONS.WARRANTY_CLAIM_CREATE,
      PERMISSIONS.WARRANTY_CLAIM_UPDATE,
      PERMISSIONS.WARRANTY_CLAIM_STATUS_UPDATE,
    ],
  },
  {
    key: "serviceCenters",
    label: "Service Centers",
    permissions: [
      PERMISSIONS.SERVICE_CENTER_VIEW,
      PERMISSIONS.SERVICE_CENTER_CREATE,
      PERMISSIONS.SERVICE_CENTER_UPDATE,
      PERMISSIONS.SERVICE_CENTER_DELETE,
    ],
  },
  {
    key: "dealers",
    label: "Dealers",
    permissions: [
      PERMISSIONS.DEALER_VIEW,
      PERMISSIONS.DEALER_CREATE,
      PERMISSIONS.DEALER_UPDATE,
      PERMISSIONS.DEALER_DELETE,
    ],
  },
  {
    key: "contentPages",
    label: "Content Pages",
    permissions: [
      PERMISSIONS.CONTENT_PAGE_VIEW,
      PERMISSIONS.CONTENT_PAGE_CREATE,
      PERMISSIONS.CONTENT_PAGE_UPDATE,
      PERMISSIONS.CONTENT_PAGE_DELETE,
    ],
  },
  {
    key: "categories",
    label: "Categories",
    permissions: [
      PERMISSIONS.CATEGORY_VIEW,
      PERMISSIONS.CATEGORY_CREATE,
      PERMISSIONS.CATEGORY_UPDATE,
      PERMISSIONS.CATEGORY_DELETE,
    ],
  },
  {
    key: "users",
    label: "Users",
    permissions: [
      PERMISSIONS.USER_VIEW,
      PERMISSIONS.USER_CREATE,
      PERMISSIONS.USER_UPDATE,
      PERMISSIONS.USER_DELETE,
      PERMISSIONS.USER_PERMISSION_MANAGE,
    ],
  },
  {
    key: "system",
    label: "System",
    permissions: [PERMISSIONS.SYSTEM_VIEW, PERMISSIONS.AUDIT_LOG_VIEW],
  },
] as const;

export const MODERATOR_PERMISSION_GROUPS = PERMISSION_GROUPS.filter(
  (group) => group.key !== "users",
);

export const MODERATOR_MANAGEABLE_PERMISSIONS: PermissionKey[] =
  MODERATOR_PERMISSION_GROUPS.flatMap((group) => [...group.permissions]);

export const ROLE_DEFAULT_PERMISSIONS: Record<UserRole, PermissionKey[]> = {
  admin: ALL_PERMISSIONS,
  moderator: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.PRODUCT_ASSIGN_OWNER,
    PERMISSIONS.WARRANTY_VIEW,
    PERMISSIONS.WARRANTY_CREATE,
    PERMISSIONS.WARRANTY_UPDATE,
    PERMISSIONS.WARRANTY_ACTIVATE,
    PERMISSIONS.WARRANTY_CLAIM_VIEW,
    PERMISSIONS.WARRANTY_CLAIM_CREATE,
    PERMISSIONS.WARRANTY_CLAIM_UPDATE,
    PERMISSIONS.WARRANTY_CLAIM_STATUS_UPDATE,
    PERMISSIONS.SERVICE_CENTER_VIEW,
    PERMISSIONS.SERVICE_CENTER_CREATE,
    PERMISSIONS.SERVICE_CENTER_UPDATE,
    PERMISSIONS.DEALER_VIEW,
    PERMISSIONS.DEALER_CREATE,
    PERMISSIONS.DEALER_UPDATE,
    PERMISSIONS.CONTENT_PAGE_VIEW,
    PERMISSIONS.CONTENT_PAGE_CREATE,
    PERMISSIONS.CONTENT_PAGE_UPDATE,
    PERMISSIONS.CATEGORY_VIEW,
    PERMISSIONS.CATEGORY_CREATE,
    PERMISSIONS.CATEGORY_UPDATE,
  ],
  customer: [
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.WARRANTY_VIEW,
    PERMISSIONS.WARRANTY_LOOKUP_OWN,
    PERMISSIONS.WARRANTY_CLAIM_CREATE,
  ],
};
