import type { UserRole } from "./roles.ts";

export const PERMISSIONS = {
  DASHBOARD_VIEW: "DASHBOARD_VIEW",

  CUSTOMER_VIEW: "CUSTOMER_VIEW",
  CUSTOMER_CREATE: "CUSTOMER_CREATE",
  CUSTOMER_UPDATE: "CUSTOMER_UPDATE",
  CUSTOMER_DELETE: "CUSTOMER_DELETE",

  PRODUCT_VIEW: "PRODUCT_VIEW",
  PRODUCT_CREATE: "PRODUCT_CREATE",
  PRODUCT_UPDATE: "PRODUCT_UPDATE",
  PRODUCT_DELETE: "PRODUCT_DELETE",
  PRODUCT_ASSIGN_OWNER: "PRODUCT_ASSIGN_OWNER",

  ACTIVATION_CODE_BATCH_VIEW: "ACTIVATION_CODE_BATCH_VIEW",
  ACTIVATION_CODE_BATCH_CREATE: "ACTIVATION_CODE_BATCH_CREATE",
  ACTIVATION_CODE_BATCH_PRINT: "ACTIVATION_CODE_BATCH_PRINT",
  ACTIVATION_CODE_BATCH_REVOKE: "ACTIVATION_CODE_BATCH_REVOKE",
  ACTIVATION_CODE_BATCH_EXTEND: "ACTIVATION_CODE_BATCH_EXTEND",
  ACTIVATION_CODE_ASSIGN_PRODUCT: "ACTIVATION_CODE_ASSIGN_PRODUCT",

  WARRANTY_VIEW: "WARRANTY_VIEW",
  WARRANTY_CREATE: "WARRANTY_CREATE",
  WARRANTY_UPDATE: "WARRANTY_UPDATE",
  WARRANTY_ACTIVATE: "WARRANTY_ACTIVATE",
  WARRANTY_VOID: "WARRANTY_VOID",
  WARRANTY_LOOKUP_OWN: "WARRANTY_LOOKUP_OWN",

  WARRANTY_CLAIM_VIEW: "WARRANTY_CLAIM_VIEW",
  WARRANTY_CLAIM_CREATE: "WARRANTY_CLAIM_CREATE",
  WARRANTY_CLAIM_UPDATE: "WARRANTY_CLAIM_UPDATE",
  WARRANTY_CLAIM_STATUS_UPDATE: "WARRANTY_CLAIM_STATUS_UPDATE",

  SERVICE_CENTER_VIEW: "SERVICE_CENTER_VIEW",
  SERVICE_CENTER_CREATE: "SERVICE_CENTER_CREATE",
  SERVICE_CENTER_UPDATE: "SERVICE_CENTER_UPDATE",
  SERVICE_CENTER_DELETE: "SERVICE_CENTER_DELETE",

  DEALER_VIEW: "DEALER_VIEW",
  DEALER_CREATE: "DEALER_CREATE",
  DEALER_UPDATE: "DEALER_UPDATE",
  DEALER_DELETE: "DEALER_DELETE",

  CONTENT_PAGE_VIEW: "CONTENT_PAGE_VIEW",
  CONTENT_PAGE_CREATE: "CONTENT_PAGE_CREATE",
  CONTENT_PAGE_UPDATE: "CONTENT_PAGE_UPDATE",
  CONTENT_PAGE_DELETE: "CONTENT_PAGE_DELETE",

  WEBSITE_CONFIG_VIEW: "WEBSITE_CONFIG_VIEW",
  WEBSITE_CONFIG_UPDATE: "WEBSITE_CONFIG_UPDATE",
  WEBSITE_CONFIG_PUBLISH: "WEBSITE_CONFIG_PUBLISH",

  CONTACT_SUBMISSION_VIEW: "CONTACT_SUBMISSION_VIEW",
  CONTACT_SUBMISSION_UPDATE: "CONTACT_SUBMISSION_UPDATE",

  CATEGORY_VIEW: "CATEGORY_VIEW",
  CATEGORY_CREATE: "CATEGORY_CREATE",
  CATEGORY_UPDATE: "CATEGORY_UPDATE",
  CATEGORY_DELETE: "CATEGORY_DELETE",

  USER_VIEW: "USER_VIEW",
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",
  USER_DELETE: "USER_DELETE",
  USER_PERMISSION_MANAGE: "USER_PERMISSION_MANAGE",

  SYSTEM_VIEW: "SYSTEM_VIEW",
  SYSTEM_CONFIG_VIEW: "SYSTEM_CONFIG_VIEW",
  SYSTEM_CONFIG_UPDATE: "SYSTEM_CONFIG_UPDATE",
  AUDIT_LOG_VIEW: "AUDIT_LOG_VIEW",
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ALL_PERMISSIONS = Object.values(PERMISSIONS);

export const PERMISSION_GROUPS = [
  {
    key: "dashboard",
    label: "Dashboard",
    permissions: [PERMISSIONS.DASHBOARD_VIEW],
  },
  {
    key: "customers",
    label: "Customers",
    permissions: [
      PERMISSIONS.CUSTOMER_VIEW,
      PERMISSIONS.CUSTOMER_CREATE,
      PERMISSIONS.CUSTOMER_UPDATE,
      PERMISSIONS.CUSTOMER_DELETE,
    ],
  },
  {
    key: "products",
    label: "Products",
    permissions: [
      PERMISSIONS.PRODUCT_VIEW,
      PERMISSIONS.PRODUCT_CREATE,
      PERMISSIONS.PRODUCT_UPDATE,
      PERMISSIONS.PRODUCT_DELETE,
      PERMISSIONS.PRODUCT_ASSIGN_OWNER,
    ],
  },
  {
    key: "warranties",
    label: "Warranties",
    permissions: [
      PERMISSIONS.WARRANTY_VIEW,
      PERMISSIONS.WARRANTY_CREATE,
      PERMISSIONS.WARRANTY_UPDATE,
      PERMISSIONS.WARRANTY_ACTIVATE,
      PERMISSIONS.WARRANTY_VOID,
      PERMISSIONS.WARRANTY_LOOKUP_OWN,
    ],
  },
  {
    key: "activationCodes",
    label: "Activation Codes",
    permissions: [
      PERMISSIONS.ACTIVATION_CODE_BATCH_VIEW,
      PERMISSIONS.ACTIVATION_CODE_BATCH_CREATE,
      PERMISSIONS.ACTIVATION_CODE_BATCH_PRINT,
      PERMISSIONS.ACTIVATION_CODE_BATCH_REVOKE,
      PERMISSIONS.ACTIVATION_CODE_BATCH_EXTEND,
      PERMISSIONS.ACTIVATION_CODE_ASSIGN_PRODUCT,
    ],
  },
  {
    key: "warrantyClaims",
    label: "Warranty Claims",
    permissions: [
      PERMISSIONS.WARRANTY_CLAIM_VIEW,
      PERMISSIONS.WARRANTY_CLAIM_CREATE,
      PERMISSIONS.WARRANTY_CLAIM_UPDATE,
      PERMISSIONS.WARRANTY_CLAIM_STATUS_UPDATE,
    ],
  },
  {
    key: "serviceCenters",
    label: "Service Centers",
    permissions: [
      PERMISSIONS.SERVICE_CENTER_VIEW,
      PERMISSIONS.SERVICE_CENTER_CREATE,
      PERMISSIONS.SERVICE_CENTER_UPDATE,
      PERMISSIONS.SERVICE_CENTER_DELETE,
    ],
  },
  {
    key: "dealers",
    label: "Dealers",
    permissions: [
      PERMISSIONS.DEALER_VIEW,
      PERMISSIONS.DEALER_CREATE,
      PERMISSIONS.DEALER_UPDATE,
      PERMISSIONS.DEALER_DELETE,
    ],
  },
  {
    key: "contentPages",
    label: "Content Pages",
    permissions: [
      PERMISSIONS.CONTENT_PAGE_VIEW,
      PERMISSIONS.CONTENT_PAGE_CREATE,
      PERMISSIONS.CONTENT_PAGE_UPDATE,
      PERMISSIONS.CONTENT_PAGE_DELETE,
    ],
  },
  {
    key: "websiteConfig",
    label: "Website Config",
    permissions: [
      PERMISSIONS.WEBSITE_CONFIG_VIEW,
      PERMISSIONS.WEBSITE_CONFIG_UPDATE,
      PERMISSIONS.WEBSITE_CONFIG_PUBLISH,
    ],
  },
  {
    key: "contactSubmissions",
    label: "Contact Submissions",
    permissions: [
      PERMISSIONS.CONTACT_SUBMISSION_VIEW,
      PERMISSIONS.CONTACT_SUBMISSION_UPDATE,
    ],
  },
  {
    key: "categories",
    label: "Categories",
    permissions: [
      PERMISSIONS.CATEGORY_VIEW,
      PERMISSIONS.CATEGORY_CREATE,
      PERMISSIONS.CATEGORY_UPDATE,
      PERMISSIONS.CATEGORY_DELETE,
    ],
  },
  {
    key: "users",
    label: "Users",
    permissions: [
      PERMISSIONS.USER_VIEW,
      PERMISSIONS.USER_CREATE,
      PERMISSIONS.USER_UPDATE,
      PERMISSIONS.USER_DELETE,
      PERMISSIONS.USER_PERMISSION_MANAGE,
    ],
  },
  {
    key: "system",
    label: "System",
    permissions: [
      PERMISSIONS.SYSTEM_VIEW,
      PERMISSIONS.SYSTEM_CONFIG_VIEW,
      PERMISSIONS.SYSTEM_CONFIG_UPDATE,
      PERMISSIONS.AUDIT_LOG_VIEW,
    ],
  },
] as const;

const MODERATOR_EXCLUDED_PERMISSIONS: ReadonlySet<PermissionKey> = new Set([
  PERMISSIONS.CUSTOMER_DELETE,
  PERMISSIONS.WARRANTY_LOOKUP_OWN,
  PERMISSIONS.SYSTEM_VIEW,
  PERMISSIONS.SYSTEM_CONFIG_VIEW,
  PERMISSIONS.SYSTEM_CONFIG_UPDATE,
  PERMISSIONS.AUDIT_LOG_VIEW,
]);

export const MODERATOR_PERMISSION_GROUPS = PERMISSION_GROUPS.flatMap(
  (group) => {
    if (group.key === "users") return [];

    const permissions = group.permissions.filter(
      (permission) => !MODERATOR_EXCLUDED_PERMISSIONS.has(permission),
    );

    return permissions.length > 0 ? [{ ...group, permissions }] : [];
  },
);

export const MODERATOR_MANAGEABLE_PERMISSIONS: PermissionKey[] =
  MODERATOR_PERMISSION_GROUPS.flatMap((group) => [...group.permissions]);

export const MODERATOR_PERMISSION_DEPENDENCIES: Partial<
  Record<PermissionKey, PermissionKey>
> = {
  [PERMISSIONS.CUSTOMER_CREATE]: PERMISSIONS.CUSTOMER_VIEW,
  [PERMISSIONS.CUSTOMER_UPDATE]: PERMISSIONS.CUSTOMER_VIEW,
  [PERMISSIONS.PRODUCT_CREATE]: PERMISSIONS.PRODUCT_VIEW,
  [PERMISSIONS.PRODUCT_UPDATE]: PERMISSIONS.PRODUCT_VIEW,
  [PERMISSIONS.PRODUCT_DELETE]: PERMISSIONS.PRODUCT_VIEW,
  [PERMISSIONS.PRODUCT_ASSIGN_OWNER]: PERMISSIONS.PRODUCT_VIEW,
  [PERMISSIONS.ACTIVATION_CODE_BATCH_CREATE]:
    PERMISSIONS.ACTIVATION_CODE_BATCH_VIEW,
  [PERMISSIONS.ACTIVATION_CODE_BATCH_PRINT]:
    PERMISSIONS.ACTIVATION_CODE_BATCH_VIEW,
  [PERMISSIONS.ACTIVATION_CODE_BATCH_REVOKE]:
    PERMISSIONS.ACTIVATION_CODE_BATCH_VIEW,
  [PERMISSIONS.ACTIVATION_CODE_BATCH_EXTEND]:
    PERMISSIONS.ACTIVATION_CODE_BATCH_VIEW,
  [PERMISSIONS.ACTIVATION_CODE_ASSIGN_PRODUCT]:
    PERMISSIONS.ACTIVATION_CODE_BATCH_VIEW,
  [PERMISSIONS.WARRANTY_CREATE]: PERMISSIONS.WARRANTY_VIEW,
  [PERMISSIONS.WARRANTY_UPDATE]: PERMISSIONS.WARRANTY_VIEW,
  [PERMISSIONS.WARRANTY_ACTIVATE]: PERMISSIONS.WARRANTY_VIEW,
  [PERMISSIONS.WARRANTY_VOID]: PERMISSIONS.WARRANTY_VIEW,
  [PERMISSIONS.WARRANTY_CLAIM_CREATE]: PERMISSIONS.WARRANTY_CLAIM_VIEW,
  [PERMISSIONS.WARRANTY_CLAIM_UPDATE]: PERMISSIONS.WARRANTY_CLAIM_VIEW,
  [PERMISSIONS.WARRANTY_CLAIM_STATUS_UPDATE]: PERMISSIONS.WARRANTY_CLAIM_VIEW,
  [PERMISSIONS.SERVICE_CENTER_CREATE]: PERMISSIONS.SERVICE_CENTER_VIEW,
  [PERMISSIONS.SERVICE_CENTER_UPDATE]: PERMISSIONS.SERVICE_CENTER_VIEW,
  [PERMISSIONS.SERVICE_CENTER_DELETE]: PERMISSIONS.SERVICE_CENTER_VIEW,
  [PERMISSIONS.DEALER_CREATE]: PERMISSIONS.DEALER_VIEW,
  [PERMISSIONS.DEALER_UPDATE]: PERMISSIONS.DEALER_VIEW,
  [PERMISSIONS.DEALER_DELETE]: PERMISSIONS.DEALER_VIEW,
  [PERMISSIONS.CONTENT_PAGE_CREATE]: PERMISSIONS.CONTENT_PAGE_VIEW,
  [PERMISSIONS.CONTENT_PAGE_UPDATE]: PERMISSIONS.CONTENT_PAGE_VIEW,
  [PERMISSIONS.CONTENT_PAGE_DELETE]: PERMISSIONS.CONTENT_PAGE_VIEW,
  [PERMISSIONS.WEBSITE_CONFIG_UPDATE]: PERMISSIONS.WEBSITE_CONFIG_VIEW,
  [PERMISSIONS.WEBSITE_CONFIG_PUBLISH]: PERMISSIONS.WEBSITE_CONFIG_VIEW,
  [PERMISSIONS.CONTACT_SUBMISSION_UPDATE]: PERMISSIONS.CONTACT_SUBMISSION_VIEW,
  [PERMISSIONS.CATEGORY_CREATE]: PERMISSIONS.CATEGORY_VIEW,
  [PERMISSIONS.CATEGORY_UPDATE]: PERMISSIONS.CATEGORY_VIEW,
  [PERMISSIONS.CATEGORY_DELETE]: PERMISSIONS.CATEGORY_VIEW,
};

export type MissingPermissionDependency = {
  permission: PermissionKey;
  requiredPermission: PermissionKey;
};

export function getMissingModeratorPermissionDependencies(
  permissions: Iterable<PermissionKey>,
): MissingPermissionDependency[] {
  const selected = new Set(permissions);

  return Object.entries(MODERATOR_PERMISSION_DEPENDENCIES).flatMap(
    ([permission, requiredPermission]) =>
      selected.has(permission as PermissionKey) &&
      !selected.has(requiredPermission)
        ? [
            {
              permission: permission as PermissionKey,
              requiredPermission,
            },
          ]
        : [],
  );
}

export const ROLE_DEFAULT_PERMISSIONS: Record<UserRole, PermissionKey[]> = {
  admin: ALL_PERMISSIONS,
  moderator: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.PRODUCT_ASSIGN_OWNER,
    PERMISSIONS.ACTIVATION_CODE_BATCH_VIEW,
    PERMISSIONS.ACTIVATION_CODE_BATCH_CREATE,
    PERMISSIONS.ACTIVATION_CODE_BATCH_PRINT,
    PERMISSIONS.ACTIVATION_CODE_ASSIGN_PRODUCT,
    PERMISSIONS.WARRANTY_VIEW,
    PERMISSIONS.WARRANTY_CREATE,
    PERMISSIONS.WARRANTY_UPDATE,
    PERMISSIONS.WARRANTY_ACTIVATE,
    PERMISSIONS.WARRANTY_CLAIM_VIEW,
    PERMISSIONS.WARRANTY_CLAIM_CREATE,
    PERMISSIONS.WARRANTY_CLAIM_UPDATE,
    PERMISSIONS.WARRANTY_CLAIM_STATUS_UPDATE,
    PERMISSIONS.SERVICE_CENTER_VIEW,
    PERMISSIONS.SERVICE_CENTER_CREATE,
    PERMISSIONS.SERVICE_CENTER_UPDATE,
    PERMISSIONS.DEALER_VIEW,
    PERMISSIONS.DEALER_CREATE,
    PERMISSIONS.DEALER_UPDATE,
    PERMISSIONS.CONTENT_PAGE_VIEW,
    PERMISSIONS.CONTENT_PAGE_CREATE,
    PERMISSIONS.CONTENT_PAGE_UPDATE,
    PERMISSIONS.WEBSITE_CONFIG_VIEW,
    PERMISSIONS.WEBSITE_CONFIG_UPDATE,
    PERMISSIONS.CONTACT_SUBMISSION_VIEW,
    PERMISSIONS.CONTACT_SUBMISSION_UPDATE,
    PERMISSIONS.CATEGORY_VIEW,
    PERMISSIONS.CATEGORY_CREATE,
    PERMISSIONS.CATEGORY_UPDATE,
  ],
  customer: [
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.WARRANTY_VIEW,
    PERMISSIONS.WARRANTY_LOOKUP_OWN,
    PERMISSIONS.WARRANTY_CLAIM_CREATE,
  ],
};
