const MIN_ADDRESS_QUERY_LENGTH = 1;
const ADDRESS_SEARCH_LIMIT = 20;
const UK_COUNTRY_CODE = 'gb';
const UK_POSTCODE_PATTERN = /^[A-Z]{1,2}\d[A-Z\d]?\s*\d[A-Z]{2}$/i;

export {
  ADDRESS_SEARCH_LIMIT,
  MIN_ADDRESS_QUERY_LENGTH,
  UK_COUNTRY_CODE,
  UK_POSTCODE_PATTERN,
};
