import type {
  CatalogFilterCategory,
  ProductCatalogItem,
} from "@/src/types/product-catalog.types";

export const productCatalog = {
  sp50: {
    id: "sp50",
    slug: "sp50-cat",
    detailKey: "sp50Cat",
    code: "SP50",
    category: "film",
    image: "/feat1.jpg",
    warrantyYears: 15,
    highlightSpecs: [
      { id: "irBlock", value: "98%" },
      { id: "uvBlock", value: "99.9%" },
    ],
    film: {
      placement: "windshield",
      vlt: "50.6%",
      vltNumber: 50.6,
      internalReflection: "7.5%",
      internalReflectionNumber: 7.5,
      externalReflection: "7.3%",
      externalReflectionNumber: 7.3,
      energyTransmission: "26.4%",
      energyTransmissionNumber: 26.4,
      energyReflection: "24.3%",
      energyReflectionNumber: 24.3,
      energyAbsorption: "49.3%",
      energyAbsorptionNumber: 49.3,
      uvBlock: "99.9%",
      uvBlockNumber: 99.9,
      irBlock: "97%",
      irBlockNumber: 97,
      heatTransferCoeff: "0.3",
      heatTransferCoeffNumber: 30,
      structure: "02 ply / 2.5 mil",
      colorId: "smokeGray",
    },
  },
  sp10: {
    id: "sp10",
    slug: "sp10-cat",
    detailKey: "sp10Cat",
    code: "SP10",
    category: "film",
    image: "/feat2.jpg",
    warrantyYears: 15,
    highlightSpecs: [
      { id: "irBlock", value: "98%" },
      { id: "vlt", value: "12.2%" },
    ],
    film: {
      placement: "sideRear",
      vlt: "12.2%",
      vltNumber: 12.2,
      internalReflection: "5%",
      internalReflectionNumber: 5,
      externalReflection: "6%",
      externalReflectionNumber: 6,
      energyTransmission: "9.6%",
      energyTransmissionNumber: 9.6,
      energyReflection: "7%",
      energyReflectionNumber: 7,
      energyAbsorption: "83.4%",
      energyAbsorptionNumber: 83.4,
      uvBlock: "99.9%",
      uvBlockNumber: 99.9,
      irBlock: "98%",
      irBlockNumber: 98,
      heatTransferCoeff: "0.15",
      heatTransferCoeffNumber: 15,
      structure: "02 ply / 2.5 mil",
      colorId: "darkCharcoal",
    },
  },
  b55: {
    id: "b55",
    slug: "b55-cat",
    detailKey: "b55Cat",
    code: "B55",
    category: "film",
    image: "/feat3.jpg",
    warrantyYears: 15,
    highlightSpecs: [
      { id: "irBlock", value: "99%" },
      { id: "vlt", value: "59.7%" },
    ],
    film: {
      placement: "windshield",
      vlt: "59.7%",
      vltNumber: 59.7,
      internalReflection: "8.2%",
      internalReflectionNumber: 8.2,
      externalReflection: "8.6%",
      externalReflectionNumber: 8.6,
      energyTransmission: "30%",
      energyTransmissionNumber: 30,
      energyReflection: "7%",
      energyReflectionNumber: 7,
      energyAbsorption: "63%",
      energyAbsorptionNumber: 63,
      uvBlock: "99.9%",
      uvBlockNumber: 99.9,
      irBlock: "99%",
      irBlockNumber: 99,
      heatTransferCoeff: "0.3",
      heatTransferCoeffNumber: 30,
      structure: "02 ply / 2 mil",
      colorId: "skyBlue",
    },
  },
  b15: {
    id: "b15",
    slug: "b15-cat",
    detailKey: "b15Cat",
    code: "B15",
    category: "film",
    image: "/feat3.jpg",
    warrantyYears: 15,
    highlightSpecs: [
      { id: "irBlock", value: "99%" },
      { id: "vlt", value: "16%" },
    ],
    film: {
      placement: "sideRear",
      vlt: "16%",
      vltNumber: 16,
      internalReflection: "5.4%",
      internalReflectionNumber: 5.4,
      externalReflection: "6.7%",
      externalReflectionNumber: 6.7,
      energyTransmission: "11.3%",
      energyTransmissionNumber: 11.3,
      energyReflection: "6.2%",
      energyReflectionNumber: 6.2,
      energyAbsorption: "82.5%",
      energyAbsorptionNumber: 82.5,
      uvBlock: "99.9%",
      uvBlockNumber: 99.9,
      irBlock: "99%",
      irBlockNumber: 99,
      heatTransferCoeff: "0.18",
      heatTransferCoeffNumber: 18,
      structure: "02 ply / 2 mil",
      colorId: "charcoalBlue",
    },
  },
  l50: {
    id: "l50",
    slug: "l50-cat",
    detailKey: "l50Cat",
    code: "L50",
    category: "film",
    image: "/sanpham/product_1.jpg",
    warrantyYears: 10,
    highlightSpecs: [
      { id: "irBlock", value: "92%" },
      { id: "vlt", value: "49%" },
    ],
    film: {
      placement: "windshield",
      vlt: "49%",
      vltNumber: 49,
      internalReflection: "7.5%",
      internalReflectionNumber: 7.5,
      externalReflection: "9.6%",
      externalReflectionNumber: 9.6,
      energyTransmission: "32%",
      energyTransmissionNumber: 32,
      energyReflection: "6.5%",
      energyReflectionNumber: 6.5,
      energyAbsorption: "61.5%",
      energyAbsorptionNumber: 61.5,
      uvBlock: "99.9%",
      uvBlockNumber: 99.9,
      irBlock: "92%",
      irBlockNumber: 92,
      heatTransferCoeff: "0.32",
      heatTransferCoeffNumber: 32,
      structure: "02 ply / 2 mil",
      colorId: "smokeGray",
    },
  },
  l15: {
    id: "l15",
    slug: "l15-cat",
    detailKey: "l15Cat",
    code: "L15",
    category: "film",
    image: "/guest/guest_2.jpg",
    warrantyYears: 10,
    highlightSpecs: [
      { id: "irBlock", value: "85%" },
      { id: "vlt", value: "15%" },
    ],
    film: {
      placement: "sideRear",
      vlt: "15%",
      vltNumber: 15,
      internalReflection: "5.3%",
      internalReflectionNumber: 5.3,
      externalReflection: "5.7%",
      externalReflectionNumber: 5.7,
      energyTransmission: "19%",
      energyTransmissionNumber: 19,
      energyReflection: "6%",
      energyReflectionNumber: 6,
      energyAbsorption: "75%",
      energyAbsorptionNumber: 75,
      uvBlock: "99.9%",
      uvBlockNumber: 99.9,
      irBlock: "85%",
      irBlockNumber: 85,
      heatTransferCoeff: "0.33",
      heatTransferCoeffNumber: 33,
      structure: "02 ply / 2 mil",
      colorId: "black",
    },
  },
  ledMini1: {
    id: "led-mini-1",
    slug: "led-mini-1",
    detailKey: "ledMini1",
    code: "LED-MINI-X1",
    category: "ledBulbs",
    image: "/sanpham/product_1.jpg",
    warrantyYears: 3,
    highlightSpecs: [
      { id: "power", value: "55W" },
      { id: "colorTemperature", value: "6000K" },
    ],
  },
  biledPro1: {
    id: "biled-pro-1",
    slug: "biled-pro-1",
    detailKey: "biledPro1",
    code: "BILED-FOG-PRO",
    category: "biLed",
    image: "/sanpham/product_3.jpg",
    warrantyYears: 3,
    highlightSpecs: [
      { id: "waterResistance", value: "IP68" },
      { id: "luminousFlux", value: "12,000 LM" },
    ],
  },
  auxLight1: {
    id: "aux-light-1",
    slug: "aux-light-1",
    detailKey: "auxLight1",
    code: "AUX-SPOT-40W",
    category: "auxLights",
    image: "/sanpham/product_6.jpg",
    warrantyYears: 2,
    highlightSpecs: [
      { id: "power", value: "40W" },
      { id: "beamDistance", value: "300m" },
    ],
  },
  dashcam4k: {
    id: "dashcam-4k",
    slug: "dashcam-4k",
    detailKey: "dashcam4k",
    code: "CAM-4K-GPS",
    category: "dashcam",
    image: "/sanpham/product_9.jpg",
    warrantyYears: 2,
    highlightSpecs: [
      { id: "resolution", value: "4K UHD" },
      { id: "sensor", value: "Sony Starvis 2" },
    ],
  },
  tpmsSolar: {
    id: "tpms-solar",
    slug: "tpms-solar",
    detailKey: "tpmsSolar",
    code: "TPMS-SOLAR-V2",
    category: "tpms",
    image: "/sanpham/product_10.jpg",
    warrantyYears: 3,
    highlightSpecs: [
      { id: "powerSource", value: "solar", translateValue: true },
      { id: "alertMode", value: "displayAndSound", translateValue: true },
    ],
  },
  androidBoxDx: {
    id: "android-box-dx",
    slug: "android-box-dx",
    detailKey: "androidBoxDx",
    code: "BOX-DX8",
    category: "androidBox",
    image: "/sanpham/product_13.jpg",
    warrantyYears: 2,
    highlightSpecs: [
      { id: "configuration", value: "RAM 8GB / ROM 128GB" },
      { id: "operatingSystem", value: "Android 13" },
    ],
  },
  retroAcc1: {
    id: "retro-acc-1",
    slug: "retro-acc-1",
    detailKey: "retroAcc1",
    code: "ACC-MANG-LED",
    category: "retroAccessories",
    image: "/sanpham/product_14.jpg",
    warrantyYears: 1,
    highlightSpecs: [
      { id: "control", value: "Bluetooth" },
      { id: "application", value: "biLedCustomization", translateValue: true },
    ],
  },
  biledLaserGt: {
    id: "biled-laser-gt",
    slug: "biled-laser-gt",
    detailKey: "biledLaserGt",
    code: "GT-LASER-90W",
    category: "biLed",
    image: "/sanpham/product_3.jpg",
    warrantyYears: 3,
    highlightSpecs: [
      { id: "power", value: "90W" },
      { id: "ledChip", value: "OSRAM" },
    ],
  },
  dashcamMini2k: {
    id: "dashcam-mini-2k",
    slug: "dashcam-mini-2k",
    detailKey: "dashcamMini2k",
    code: "CAM-2K-MINI",
    category: "dashcam",
    image: "/sanpham/product_9.jpg",
    warrantyYears: 2,
    highlightSpecs: [
      { id: "resolution", value: "2K 1440P" },
      { id: "connectivity", value: "WiFi 6" },
    ],
  },
  tpmsSolarPro: {
    id: "tpms-solar-pro",
    slug: "tpms-solar-pro",
    detailKey: "tpmsSolarPro",
    code: "TPMS-PRO-EXT",
    category: "tpms",
    image: "/sanpham/product_10.jpg",
    warrantyYears: 2,
    highlightSpecs: [
      { id: "valveType", value: "external", translateValue: true },
      { id: "connectivity", value: "Bluetooth 5.0" },
    ],
  },
} as const satisfies Record<string, ProductCatalogItem>;

export const productCatalogItems = Object.values(productCatalog);

export const catalogCategories: readonly CatalogFilterCategory[] = [
  "all",
  "film",
  "ledBulbs",
  "biLed",
  "auxLights",
  "dashcam",
  "tpms",
  "androidBox",
  "retroAccessories",
];

export function findProductBySlug(
  slug: string,
): ProductCatalogItem | undefined {
  const normalizedSlug = slug.toLowerCase();
  return productCatalogItems.find(
    (product) =>
      product.slug === normalizedSlug ||
      product.id === normalizedSlug ||
      product.slug.replace("-cat", "") === normalizedSlug.replace("-cat", ""),
  );
}
