export const APP_ROUTES = {
  home: "/",
  about: "/about",
  products: "/products",
  product: (slug: string) => ({
    pathname: "/products/[slug]" as const,
    params: { slug },
  }),
  warranty: "/warranty",
  warrantyLookup: "/warranty/lookup",
  warrantyActivate: "/warranty/activate",
  warrantyRequest: "/warranty/request",
  warrantyTrack: "/warranty/track",
  dealers: "/dealers",
  supportCenters: "/support-centers",
  contact: "/contact",
  guide: "/guide",
  policies: "/policies",
  policyGeneral: "/policies/general",
  policyPrivacy: "/policies/privacy",
  policyPurchasing: "/policies/purchasing",
  policyWarrantyReturn: "/policies/warranty-return",
  policyShipping: "/policies/shipping",
  policyPayment: "/policies/payment",
} as const;
