ALTER TYPE "permission_key" ADD VALUE IF NOT EXISTS 'ACTIVATION_CODE_BATCH_VIEW';
ALTER TYPE "permission_key" ADD VALUE IF NOT EXISTS 'ACTIVATION_CODE_BATCH_CREATE';
ALTER TYPE "permission_key" ADD VALUE IF NOT EXISTS 'ACTIVATION_CODE_BATCH_PRINT';
ALTER TYPE "permission_key" ADD VALUE IF NOT EXISTS 'ACTIVATION_CODE_BATCH_REVOKE';
ALTER TYPE "permission_key" ADD VALUE IF NOT EXISTS 'SYSTEM_CONFIG_VIEW';
ALTER TYPE "permission_key" ADD VALUE IF NOT EXISTS 'SYSTEM_CONFIG_UPDATE';
